service: aws-node-dynamodb

disabledDeprecations:
   - '*'

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:392664342342:table/TodoTable

# plugins:
#   - serverless-plugin-common-excludes 
#   - serverless-plugin-include-dependencies

functions:
  addTodo:
    handler: src/addTodo.handler
    events:
      - http:
          path: /addTodo
          method: post

  fetchTodos:
    handler: src/fetchTodos.handler
    events:
      - http:
          path: /todos
          method: get

  fetchTodo:
    handler: src/fetchTodo.handler
    events:
      - http:
          path: /todo/{id}
          method: get

  updateTodo:
    handler: src/updateTodo.handler
    events:
      - http:
          path: /updateTodo/{id}
          method: put
  
  


resources:
  Resources:
    ToDoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH

          